name: QA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-qa:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        run: |
          pip install -U pip
          pip install -e .[qa,scripts,test]

      - name: Check Linting
        run: inv check-lint

      - name: Check Formatting
        run: inv check-format

      - name: Check Type
        run: inv check-type
